"""Frontend lane guard: show which side of the three parallel workstreams each dirty file is on.

Run from the workspace root:

    py -3.12 tools/check_frontend_lanes.py --lane 3
    py -3.12 tools/check_frontend_lanes.py            # classify only, no cross-lane verdict

The lane map below must stay in sync with nanhang-app/docs/PARALLEL_FRONTEND.md (section 一/二).
Three agents share ONE working tree, so the failure mode is not a merge conflict: whoever writes
from a stale snapshot silently overwrites the others. This check only makes that visible; the
rules themselves (re-read before writing, never `git add -A`, never commit another lane's files)
are in the document.
"""
from pathlib import Path
import argparse
import fnmatch
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
WEB = "nanhang-app/apps/web/"

# Exclusive ownership: exactly one lane may write these.
LANES = {
    "1": {
        "name": "定位/成绩与交付",
        "files": [
            WEB + "src/chapters/locate.tsx", WEB + "src/chapters/axis.tsx", WEB + "src/chapters/sail.tsx",
            WEB + "src/quality-huixi.ts", WEB + "src/quality-types.ts", WEB + "src/exam-position.ts",
            WEB + "src/reference-lines.ts", WEB + "src/progress.ts",
            WEB + "test/exam-position.test.ts", WEB + "test/quality-huixi.test.ts",
            WEB + "test/progress.test.ts", WEB + "test/release-integration.test.ts",
            # 20:1x 起由线一接手院校卡分层标签（原先登记在线三名下）。
            WEB + "src/chapters/chart.tsx",
            # 顶栏 ≤340px 不变量：钉的是 style.css 的顶栏专项块，按内容推定为线一。
            WEB + "test/topbar-narrow.test.ts",
            "nanhang-app/docs/**", WEB + "VISUAL_PROGRESS.md",
        ],
    },
    "2": {
        "name": "方向与双线",
        "files": [
            WEB + "src/chapters/direction.tsx", WEB + "src/journey-model.ts",
        ],
    },
    "3": {
        "name": "设置与图形",
        "files": [
            WEB + "src/chapters/settings.tsx", WEB + "src/chapters/sail.tsx",
            WEB + "src/art.tsx", WEB + "src/chat.tsx", WEB + "test/settings.test.ts",
            WEB + "test/sail-deck.test.ts", WEB + "test/sail-pack.test.ts",
        ],
    },
}

# Any lane may touch these, one writer at a time, after claiming in the registry.
SHARED = [
    WEB + "src/App.tsx", WEB + "src/style.css", WEB + "src/model.ts",
    WEB + "src/chapters/talk.tsx", WEB + "src/chapters/shared.ts",
    WEB + "src/ai-panel.ts", WEB + "src/ai-client.ts", WEB + "src/theme.tsx",
    # 这份分工表本身就是三线共用的登记处：谁都能追加认领行。
    "nanhang-app/docs/PARALLEL_FRONTEND.md",
    # 文档规范要求每条线都写实施记录、都更新进度主本：它们是共享的，不是线一独占。
    "nanhang-app/docs/IMPLEMENTATION_LOG.md", "nanhang-app/docs/project-status.json",
]

# Regenerated by tools/sync_project_docs.py; nobody edits these by hand.
GENERATED = ["MANIFEST.sha256", "FILE_INDEX.md", "releases/*.sha256",
             "nanhang-app/docs/baseline/**", "nanhang-app/docs/verification/**"]

# Workspace-level tooling and rules: outside the three frontend lanes.
NEUTRAL = ["tools/**", "AGENTS.md", "README.md"]


def dirty_paths():
    """Every staged or unstaged path in git status, as repo-relative posix paths."""
    result = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit("git status failed: " + result.stderr.strip())
    rows = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        state, path = line[:2], line[3:].strip()
        if " -> " in path:  # rename: classify the destination
            path = path.split(" -> ", 1)[1]
        rows.append((state, path.replace("\\", "/")))
    return rows


def matches(path, patterns):
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


STATUS_MARKERS = ("<!-- PROJECT-STATUS:START -->", "<!-- PROJECT-STATUS:END -->")


def summary_only(path):
    """True when a document's diff is confined to the PROJECT-STATUS notice block.

    tools/sync_project_docs.py rewrites that block in every managed document from
    docs/project-status.json, so whoever runs the sync will always leave a dozen documents dirty.
    Those edits are generated output; only the prose outside the block belongs to a lane.
    """
    for args in (["git", "diff", "-U0", "--", path], ["git", "diff", "--cached", "-U0", "--", path]):
        diff = subprocess.run(args, cwd=ROOT, capture_output=True, text=True).stdout
        if not diff.strip():
            continue
        for line in diff.splitlines():
            if line[:1] not in "+-" or line.startswith(("+++", "---")):
                continue
            body = line[1:].strip()
            if not body.startswith(">") and body not in STATUS_MARKERS:
                return False
        return True
    return False


def owner(path):
    # Shared wins over the lane lists: a file named by both is by definition not exclusive.
    if matches(path, SHARED):
        return "shared", None
    # Generated output wins over the lane prose glob: docs/baseline/** and docs/verification/**
    # are produced by the sync tool and by verification runs, not written by hand.
    if matches(path, GENERATED):
        return "generated", None
    for lane, spec in LANES.items():
        if matches(path, spec["files"]):
            return "lane", lane
    if matches(path, NEUTRAL):
        return "neutral", None
    return "unregistered", None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--lane", choices=sorted(LANES), help="your lane: flag anything outside it")
    args = parser.parse_args()

    rows = dirty_paths()
    if not rows:
        print("工作区干净：没有未提交的改动。")
        return 0

    buckets = {"mine": [], "shared": [], "other": [], "generated": [], "sync": [], "neutral": [], "unregistered": []}
    staged_foreign = []
    for state, path in rows:
        kind, lane = owner(path)
        if kind == "shared":
            buckets["shared"].append(path)
        elif kind == "generated":
            buckets["generated"].append(path)
        elif kind == "neutral":
            buckets["neutral"].append(path)
        elif kind == "unregistered":
            buckets["unregistered"].append(path)
        elif path.endswith(".md") and summary_only(path):
            buckets["sync"].append(path)
        elif args.lane is None:
            buckets["mine" if kind == "lane" else "other"].append(path)
        elif lane == args.lane:
            buckets["mine"].append(path)
        else:
            buckets["other"].append(f"{path}（线 {lane} · {LANES[lane]['name']}）")
            if state[0] != " " and state[0] != "?":  # already staged: a commit would carry it along
                staged_foreign.append(path)

    if args.lane:
        print(f"本线 = 线 {args.lane} · {LANES[args.lane]['name']}")
    else:
        for lane, spec in LANES.items():
            owned = [path for state, path in rows if owner(path) == ("lane", lane)]
            if owned:
                print(f"线 {lane} · {spec['name']}：{len(owned)} 个文件")
    labels = [
        ("mine", "本线（可安全提交）"),
        ("shared", "共享文件（写前重读；确认没有别人正在改）"),
        ("other", "其它线（不要 add、不要 commit、不要回滚）"),
        ("generated", "生成物（应由 sync_project_docs.py 产出，跑完用 --check 复核）"),
        ("sync", "文档摘要块（同步工具按 project-status.json 重写，跟着本轮一起提交即可）"),
        ("neutral", "工作区工具与规范（不属三条前端线）"),
        ("unregistered", "未登记（要么补进 PARALLEL_FRONTEND.md，要么确认不是本工程的改动）"),
    ]
    for key, label in labels:
        if buckets[key]:
            print(f"\n[{label}]")
            for path in buckets[key]:
                print("  " + path)

    if staged_foreign:
        print("\n错误：暂存区里有别的线的文件，提交会把它们一起带走：")
        for path in staged_foreign:
            print("  " + path)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
