export type RankInterval = readonly [best: number, worst: number];

export type ReasonCode =
  | "INCOMPLETE_SUBJECTS"
  | "SUBJECT_REQUIREMENT_FAILED"
  | "UNKNOWN_REQUIREMENT"
  | "UNSUPPORTED_SCOPE"
  | "SCHOOL_SCORE_UNCALIBRATED"
  | "TOTAL_NOT_SOURCE"
  | "UNKNOWN_SCORE_BASIS"
  | "BONUS_BASIS_MISMATCH"
  | "RANK_CONFLICT"
  | "NO_OBSERVED_SCORE"
  | "OUT_OF_DISTRIBUTION_COVERAGE"
  | "MAJOR_HISTORY_MISSING"
  | "GROUP_HISTORY_MISSING"
  | "GROUP_CHANGED"
  | "SOURCE_CONFLICT"
  | "TARGET_YEAR_PLAN_MISSING"
  | "DATASET_WITHDRAWN"
  | "TUITION_UNKNOWN"
  | "HARD_PREFERENCE_EXCLUDED"
  | "NO_ACADEMIC_INPUT"
  | "NO_CALIBRATION_MODEL";

export type TriState = "PASS" | "FAIL" | "UNKNOWN";

export type ReferenceRelation =
  | "AHEAD_OF_REFERENCE"
  | "BEHIND_REFERENCE"
  | "OVERLAPS_REFERENCE"
  | "NOT_COMPARABLE";
